[package]
name = "windows-awake"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.11"
windows = { version = "0.59.0", features = ["Win32_System_Power"] }

[[example]]
name = "power_management_demo"
path = "examples/main.rs"
